### ISSUE TITLE
TypeError: argument 'include_pixel': Shape Mismatch:

### ISSUE THREAD

**Issue by aertist** [pierogis/pierogis#7] opened 2021-02-03 16:45 UTC
Input:

`pyrogis chef hut.png "sort; quantize" -o out_hut.png`

Output:

`Traceback (most recent call last):
  File "c:\users\spectre\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\spectre\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\SPECTRE\anaconda3\Scripts\pyrogis.exe\__main__.py", line 7, in <module>
  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\__main__.py", line 81, in main
    cooked_dish = create_dish(path, add_dish_desc, parsed_vars)  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\__main__.py", line 59, in create_dish
    return chef.cook_dish_desc(dish_desc)
  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\chef.py", line 370, in cook_dish_desc
    recipe = self.create_recipe_object(ingredients, seasoning_links, recipe_order)
  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\chef.py", line 352, in create_recipe_object
    seasoning.season(ingredient)
  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\ingredients\seasonings\seasoning.py", line 51, in season
    recipient.mask = self.cook(recipient_pixels)
  File "c:\users\spectre\anaconda3\lib\site-packages\pyrogis\ingredients\seasonings\threshold.py", line 43, in cook
    cooked_pixels = recipes.threshold(
TypeError: argument 'include_pixel': Shape Mismatch:
 from=(dim=1, dtype=Int32), to=(dim=1, dtype=Int64)`

**Comment by ksmoore17** [comment] 2021-02-03 16:55
Good stuff thanks for the issue. This is caused by the python -> rust binding for the threshold ingredient which is used by sort. Something like the rust side expects an int 64, but it looks like numpy on windows is passes an int32 array by default. I'm working on a fix now.

**Comment by aertist** [comment] 2021-02-03 17:10
The readme is confusing af for a newbie like me. Can you make a YT tutorial on how to use all the args? 😅

**Comment by ksmoore17** [comment] 2021-02-03 18:54
Yes, hopefully sooner than later... many things on the way. I'm glad that you are trying it in these early stages, as you can tell I'm still transitioning it from something I know how to use to something others can use. 

I just tested a fix on windows and it should be working. You can `pip install pyrogis` again and the error should be fixed. Let me know

**Comment by StrangerMersault** [comment] 2021-02-04 23:36
Chiming in with the same error in Windows:

```
Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\***\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\Scripts\pyrogis.exe\__main__.py", line 7, in <module>
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\__main__.py", line 81, in main
    cooked_dish = create_dish(path, add_dish_desc, parsed_vars)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\__main__.py", line 59, in create_dish
    return chef.cook_dish_desc(dish_desc)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\chef.py", line 370, in cook_dish_desc
    recipe = self.create_recipe_object(ingredients, seasoning_links, recipe_order)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\chef.py", line 352, in create_recipe_object
    seasoning.season(ingredient)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\ingredients\seasonings\seasoning.py", line 51, in season
    recipient.mask = self.cook(recipient_pixels)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pyrogis\ingredients\seasonings\threshold.py", line 43, in cook
    cooked_pixels = recipes.threshold(
TypeError: argument 'include_pixel': Shape Mismatch:
 from=(dim=1, dtype=Int32), to=(dim=1, dtype=Int64)
```

**Comment by ksmoore17** [comment] 2021-02-04 23:49
Thank you for letting me know! Can you give me a `pip list` and tell me the version of pyrogis? Should be 0.1.3 and if it's 0.1.2: `pip uninstall pyrogis` then `pip install pyrogis --no-cache-dir`. If you already tried reinstalling it may be installing the old version from your pip cache.

**Comment by ksmoore17** [comment] 2021-02-23 08:06
Closing: I didn't hear back, but I think this is no longer a problem from my own tests.

**Closed** 2021-02-23 08:05 UTC
